version: '3'

services:
  jekyll:
    image: jekyll/jekyll
    command: >
      bash -c "bundle install &&
               bundle exec jekyll serve --host 0.0.0.0"
    volumes:
      - .:/srv/jekyll
    ports:
      - "4000:4000"
